name: Windows

on:
  push:
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
  schedule:
    - cron:  '0 8 * * *'

permissions:
  contents: read

jobs:
  run-tests:
    name: Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Test with pytest
      run: |
        pytest pyderman/test.py
